import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Google Cloud Dataflow Pipeline with Apache Beam & GCS\n",
                "\n",
                "This project is wrapped and managed using **`uv`** (Python 3.12, keyless ADC authentication, GCP Free Tier compatible).\n",
                "\n",
                "### Quick Start with `uv`:\n",
                "- **Kernel**: Select the kernel **`Python (uv: GCP Dataflow)`** or choose the interpreter at `.venv/Scripts/python.exe`.\n",
                "- **Run via CLI**:\n",
                "  ```bash\n",
                "  uv run python -m gcp.pipeline\n",
                "  ```\n",
                "- **Add new dependencies**:\n",
                "  ```bash\n",
                "  uv add <package-name>\n",
                "  ```\n",
                "\n",
                "### Keyless Authentication (Free Tier):\n",
                "No service account JSON key files required. Authenticate using your user credentials via `gcloud`:\n",
                "```bash\n",
                "gcloud auth login\n",
                "gcloud auth application-default login\n",
                "gcloud config set project <YOUR_GCP_PROJECT_ID>\n",
                "gcloud auth application-default set-quota-project <YOUR_GCP_PROJECT_ID>\n",
                "```\n",
                "\n",
                "### Pipeline Architecture:\n",
                "1. **Input**: `Employers_data.csv` stored in Google Cloud Storage (`gs://<YOUR_BUCKET_NAME>/input/Employers_data.csv`)\n",
                "2. **Processing (Apache Beam)**:\n",
                "   - Read CSV lines and skip header\n",
                "   - Parse and cast columns (`Employee_ID`, `Name`, `Age`, `Department`, `Salary`, etc.)\n",
                "   - Extract Key-Value pairs: `(Department, Salary)`\n",
                "   - Aggregate metrics: compute **Average Salary per Department**\n",
                "   - Format results into CSV format\n",
                "3. **Output Sink**: Partitioned output files written back to GCS (`gs://<YOUR_BUCKET_NAME>/output/department_salary_summary-*.csv`)\n",
                "4. **Execution Runners**:\n",
                "   - **DirectRunner**: For local testing and validation\n",
                "   - **DataflowRunner**: For fully managed, distributed execution on Google Cloud Platform"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 1: Environment check (managed by uv)\n",
                "# Note: When running in VS Code or Jupyter, select the kernel: 'Python (uv: GCP Dataflow)'\n",
                "# If running in an external notebook like Google Colab, uncomment the line below:\n",
                "# !pip install --quiet \"apache-beam[gcp]\" google-cloud-storage google-auth pandas\n",
                "\n",
                "import sys\n",
                "print(f\"Python Executable: {sys.executable}\")\n",
                "print(\"Project dependencies are managed by uv (.venv).\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2: Import required modules and libraries\n",
                "import os\n",
                "import csv\n",
                "import json\n",
                "import logging\n",
                "import glob\n",
                "import google.auth\n",
                "from google.cloud import storage\n",
                "import apache_beam as beam\n",
                "from apache_beam.options.pipeline_options import (\n",
                "    PipelineOptions,\n",
                "    GoogleCloudOptions,\n",
                "    StandardOptions,\n",
                "    SetupOptions,\n",
                "    WorkerOptions\n",
                ")\n",
                "import apache_beam.transforms.combiners as combiners\n",
                "\n",
                "logging.basicConfig(level=logging.INFO)\n",
                "print(f\"Apache Beam version: {beam.__version__}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Cell 3: Configure GCP Project & Verify Authentication (Keyless ADC)\n",
                "Since you are using the GCP Free Tier, no service account key file is required. The Google Cloud client libraries automatically use your **Application Default Credentials (ADC)**."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3: GCP Configuration (Keyless / Free Tier)\n",
                "# =====================================================================\n",
                "# UPDATE THE PLACEHOLDER VALUES BELOW WITH YOUR GCP PROJECT DETAILS\n",
                "# =====================================================================\n",
                "\n",
                "# 1. Google Cloud Project ID\n",
                "PROJECT_ID = \"YOUR_GCP_PROJECT_ID\"  # e.g., \"my-cloud-project-12345\"\n",
                "\n",
                "# 2. Google Cloud Storage Bucket Name (omit 'gs://')\n",
                "BUCKET_NAME = \"YOUR_GCS_BUCKET_NAME\"  # e.g., \"my-company-dataflow-bucket\"\n",
                "\n",
                "# 3. Compute Region for Dataflow execution (us-central1 is standard for free tier)\n",
                "REGION = \"us-central1\"  # e.g., \"us-central1\", \"us-east1\", \"europe-west1\"\n",
                "\n",
                "# 4. Check and verify Application Default Credentials (ADC)\n",
                "try:\n",
                "    credentials, detected_project = google.auth.default()\n",
                "    print(\"SUCCESS: Authenticated via Application Default Credentials (ADC).\")\n",
                "    if detected_project:\n",
                "        print(f\"Default detected project: {detected_project}\")\n",
                "except Exception as e:\n",
                "    print(f\"ADC Notice: {e}\")\n",
                "    print(\"To authenticate without a key, run in your terminal:\")\n",
                "    print(\"  gcloud auth application-default login\")\n",
                "\n",
                "# 5. Cloud Storage Paths for Dataflow\n",
                "INPUT_GCS_PATH = f\"gs://{BUCKET_NAME}/input/Employers_data.csv\"\n",
                "OUTPUT_GCS_PATH = f\"gs://{BUCKET_NAME}/output/department_salary_summary\"\n",
                "STAGING_LOCATION = f\"gs://{BUCKET_NAME}/staging\"\n",
                "TEMP_LOCATION = f\"gs://{BUCKET_NAME}/temp\"\n",
                "JOB_NAME = \"employee-salary-dataflow-job\"\n",
                "\n",
                "print(\"\\n--- GCP Pipeline Configuration ---\")\n",
                "print(f\"Project ID:       {PROJECT_ID}\")\n",
                "print(f\"Bucket Name:      {BUCKET_NAME}\")\n",
                "print(f\"Region:           {REGION}\")\n",
                "print(f\"Input GCS:        {INPUT_GCS_PATH}\")\n",
                "print(f\"Output GCS:       {OUTPUT_GCS_PATH}\")\n",
                "print(f\"Staging Location: {STAGING_LOCATION}\")\n",
                "print(f\"Temp Location:    {TEMP_LOCATION}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4: Upload Local CSV to Google Cloud Storage (Utility)\n",
                "# Helper function to upload 'SourceFiles/Employers_data.csv' to your GCS bucket\n",
                "# (Uses ADC - no service account key needed)\n",
                "\n",
                "def upload_local_file_to_gcs(local_path: str, bucket_name: str, target_blob_name: str):\n",
                "    \"\"\"Uploads a local file to a GCS bucket using user ADC credentials.\"\"\"\n",
                "    try:\n",
                "        client = storage.Client(project=PROJECT_ID)\n",
                "        bucket = client.bucket(bucket_name)\n",
                "        blob = bucket.blob(target_blob_name)\n",
                "        blob.upload_from_filename(local_path)\n",
                "        print(f\"Uploaded '{local_path}' to 'gs://{bucket_name}/{target_blob_name}' successfully.\")\n",
                "    except Exception as err:\n",
                "        print(f\"Upload error: {err}\")\n",
                "\n",
                "# Locate local Employers_data.csv\n",
                "local_candidates = [\"../SourceFiles/Employers_data.csv\", \"SourceFiles/Employers_data.csv\"]\n",
                "local_csv_path = next((p for p in local_candidates if os.path.exists(p)), None)\n",
                "\n",
                "if local_csv_path:\n",
                "    print(f\"Found source file: {local_csv_path}\")\n",
                "    # Uncomment the line below once BUCKET_NAME is created and ADC is logged in:\n",
                "    # upload_local_file_to_gcs(local_csv_path, BUCKET_NAME, \"input/Employers_data.csv\")\n",
                "else:\n",
                "    print(\"Could not locate 'Employers_data.csv'. Please check the path.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5: Define Apache Beam Transformation Classes (DoFn)\n",
                "\n",
                "class ParseAndCleanEmployeeDoFn(beam.DoFn):\n",
                "    \"\"\"\n",
                "    Parses CSV lines, skips header row, handles basic cleansing, and casts types.\n",
                "    Fields: Employee_ID,Name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary\n",
                "    \"\"\"\n",
                "    def process(self, line: str):\n",
                "        line = line.strip()\n",
                "        if not line or line.startswith(\"Employee_ID\"):\n",
                "            return\n",
                "        \n",
                "        reader = csv.reader([line])\n",
                "        for row in reader:\n",
                "            if len(row) >= 10:\n",
                "                try:\n",
                "                    yield {\n",
                "                        \"employee_id\": int(row[0].strip()),\n",
                "                        \"name\": row[1].strip(),\n",
                "                        \"age\": int(row[2].strip()),\n",
                "                        \"gender\": row[3].strip(),\n",
                "                        \"department\": row[4].strip(),\n",
                "                        \"job_title\": row[5].strip(),\n",
                "                        \"experience_years\": int(row[6].strip()),\n",
                "                        \"education_level\": row[7].strip(),\n",
                "                        \"location\": row[8].strip(),\n",
                "                        \"salary\": float(row[9].strip()),\n",
                "                    }\n",
                "                except (ValueError, IndexError):\n",
                "                    # Skip rows with malformed numeric values\n",
                "                    continue\n",
                "\n",
                "\n",
                "class ExtractDepartmentSalaryDoFn(beam.DoFn):\n",
                "    \"\"\"Extracts (department, salary) tuples for key-based aggregation.\"\"\"\n",
                "    def process(self, record: dict):\n",
                "        yield (record[\"department\"], record[\"salary\"])\n",
                "\n",
                "\n",
                "class FormatSummaryStatsDoFn(beam.DoFn):\n",
                "    \"\"\"Formats (department, average_salary) tuple into a CSV line.\"\"\"\n",
                "    def process(self, element):\n",
                "        department, avg_salary = element\n",
                "        yield f\"{department},{avg_salary:.2f}\""
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 6: Test Apache Beam Pipeline Locally (DirectRunner)\n",
                "# Run this locally before launching on GCP Dataflow to verify transformations\n",
                "# (Requires NO GCP connection - 100% free and offline)\n",
                "\n",
                "local_test_file = next((p for p in [\"../SourceFiles/Employers_data.csv\", \"SourceFiles/Employers_data.csv\"] if os.path.exists(p)), None)\n",
                "local_out_dir = \"./local_output\"\n",
                "os.makedirs(local_out_dir, exist_ok=True)\n",
                "local_output_prefix = os.path.join(local_out_dir, \"dept_salary_summary\")\n",
                "\n",
                "print(\"Executing local pipeline with DirectRunner...\")\n",
                "with beam.Pipeline(runner=\"DirectRunner\") as p:\n",
                "    (\n",
                "        p\n",
                "        | \"ReadLocalCSV\" >> beam.io.ReadFromText(local_test_file)\n",
                "        | \"ParseCleanRecords\" >> beam.ParDo(ParseAndCleanEmployeeDoFn())\n",
                "        | \"ExtractDeptSalary\" >> beam.ParDo(ExtractDepartmentSalaryDoFn())\n",
                "        | \"ComputeAvgSalary\" >> combiners.Mean.PerKey()\n",
                "        | \"FormatResults\" >> beam.ParDo(FormatSummaryStatsDoFn())\n",
                "        | \"WriteLocalOutput\" >> beam.io.WriteToText(\n",
                "            file_path_prefix=local_output_prefix,\n",
                "            file_name_suffix=\".csv\",\n",
                "            header=\"Department,Average_Salary\"\n",
                "        )\n",
                "    )\n",
                "\n",
                "print(\"Local test run finished! Checking output:\")\n",
                "out_files = glob.glob(f\"{local_output_prefix}*\")\n",
                "for fpath in out_files:\n",
                "    print(f\"\\n--- {fpath} ---\")\n",
                "    with open(fpath, \"r\") as f:\n",
                "        print(f.read().strip())"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Cell 7: Configure Dataflow Pipeline Options (Free Tier Friendly)\n",
                "\n",
                "When submitting to Dataflow:\n",
                "1. Your local client uses **ADC** to submit the job.\n",
                "2. The Dataflow worker VMs in GCP automatically run under your project's **Compute Engine default service account** (`<PROJECT_NUMBER>-compute@developer.gserviceaccount.com`).\n",
                "\n",
                "> **One-time IAM setup (if needed)**:\n",
                "> Ensure the default Compute Engine service account has the `Dataflow Worker` and `Storage Object Admin` roles:\n",
                "> ```bash\n",
                "> PROJECT_NUMBER=$(gcloud projects describe YOUR_GCP_PROJECT_ID --format=\"value(projectNumber)\")\n",
                "> gcloud projects add-iam-policy-binding YOUR_GCP_PROJECT_ID \\\n",
                ">     --member=\"serviceAccount:${PROJECT_NUMBER}-compute@developer.gserviceaccount.com\" \\\n",
                ">     --role=\"roles/dataflow.worker\"\n",
                "> gcloud projects add-iam-policy-binding YOUR_GCP_PROJECT_ID \\\n",
                ">     --member=\"serviceAccount:${PROJECT_NUMBER}-compute@developer.gserviceaccount.com\" \\\n",
                ">     --role=\"roles/storage.objectAdmin\"\n",
                "> ```"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 7: Configure GCP Dataflow Pipeline Options\n",
                "\n",
                "dataflow_pipeline_args = [\n",
                "    f\"--project={PROJECT_ID}\",\n",
                "    f\"--region={REGION}\",\n",
                "    \"--runner=DataflowRunner\",\n",
                "    f\"--staging_location={STAGING_LOCATION}\",\n",
                "    f\"--temp_location={TEMP_LOCATION}\",\n",
                "    f\"--job_name={JOB_NAME}\",\n",
                "    \"--save_main_session\",  # Essential for serialization of functions & classes in __main__\n",
                "    # Cost-effective worker settings for Free Tier / small batches:\n",
                "    \"--worker_machine_type=e2-standard-2\",\n",
                "    \"--num_workers=1\",\n",
                "    \"--max_num_workers=2\"\n",
                "]\n",
                "\n",
                "dataflow_options = PipelineOptions(dataflow_pipeline_args)\n",
                "print(\"Dataflow pipeline options configured successfully for Free Tier.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 8: Submit & Execute Apache Beam Pipeline on GCP Dataflow\n",
                "# =====================================================================\n",
                "# Note: Make sure you have created your GCS bucket and uploaded\n",
                "# 'Employers_data.csv' to INPUT_GCS_PATH before running this cell.\n",
                "# =====================================================================\n",
                "\n",
                "print(f\"Submitting Dataflow Job '{JOB_NAME}' to GCP Project '{PROJECT_ID}'...\")\n",
                "print(f\"Reading input from: {INPUT_GCS_PATH}\")\n",
                "print(f\"Writing output to:  {OUTPUT_GCS_PATH}\")\n",
                "\n",
                "try:\n",
                "    with beam.Pipeline(options=dataflow_options) as p:\n",
                "        (\n",
                "            p\n",
                "            | \"ReadGCSInput\" >> beam.io.ReadFromText(INPUT_GCS_PATH)\n",
                "            | \"ParseAndClean\" >> beam.ParDo(ParseAndCleanEmployeeDoFn())\n",
                "            | \"ExtractDeptSalary\" >> beam.ParDo(ExtractDepartmentSalaryDoFn())\n",
                "            | \"ComputeAvgSalary\" >> combiners.Mean.PerKey()\n",
                "            | \"FormatResults\" >> beam.ParDo(FormatSummaryStatsDoFn())\n",
                "            | \"WriteGCSOutput\" >> beam.io.WriteToText(\n",
                "                file_path_prefix=OUTPUT_GCS_PATH,\n",
                "                file_name_suffix=\".csv\",\n",
                "                header=\"Department,Average_Salary\"\n",
                "            )\n",
                "        )\n",
                "    print(\"\\nDataflow job finished or submitted! Visit Google Cloud Console -> Dataflow to view job progress.\")\n",
                "except Exception as err:\n",
                "    print(f\"\\nJob execution status / error: {err}\")\n",
                "    print(\"Verify your GCP project ID, bucket permissions, and GCS input path.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 9: Verify and Inspect Output Files from Google Cloud Storage\n",
                "# (Uses user ADC credentials directly)\n",
                "\n",
                "def inspect_gcs_results(bucket_name: str, prefix: str):\n",
                "    \"\"\"Lists and prints the contents of generated output files in GCS.\"\"\"\n",
                "    try:\n",
                "        client = storage.Client(project=PROJECT_ID)\n",
                "        bucket = client.bucket(bucket_name)\n",
                "        blobs = list(bucket.list_blobs(prefix=prefix))\n",
                "        \n",
                "        if not blobs:\n",
                "            print(f\"No output files found under prefix: '{prefix}'\")\n",
                "            return\n",
                "            \n",
                "        print(f\"Found {len(blobs)} output partition file(s) in GCS:\")\n",
                "        for blob in blobs:\n",
                "            print(f\"\\nBlob: gs://{bucket_name}/{blob.name}\")\n",
                "            content = blob.download_as_text()\n",
                "            print(content[:500])\n",
                "    except Exception as err:\n",
                "        print(f\"GCS inspection error: {err}\")\n",
                "\n",
                "# Uncomment the line below after your Dataflow job completes successfully:\n",
                "# inspect_gcs_results(BUCKET_NAME, \"output/department_salary_summary\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python (.venv: GCP Dataflow 3.12)",
            "language": "python",
            "name": "gcp-dataflow-venv"
        },
        "language_info": {
            "name": "python",
            "version": "3.12.14"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Write to PythonNotebook/1.ipynb
target_path_1 = "c:/Debaranjan/Git_Projects/GCP/PythonNotebook/1.ipynb"
with open(target_path_1, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)
print(f"Successfully wrote {target_path_1}")

# Also write to root 1.ipynb for convenience
target_path_2 = "c:/Debaranjan/Git_Projects/GCP/1.ipynb"
with open(target_path_2, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)
print(f"Successfully wrote {target_path_2}")
